services:
  - type: web
    name: ats-resume-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
